#!/usr/local/opt/php56/bin/php
<?php

error_reporting ( 0 );
ini_set( "display_error" , false );

$sudo = "/usr/bin/sudo";
$pcode = trim( $argv[1] );
$user = get_current_user();
$wp = "/usr/local/bin/wp";
$mysql = "/usr/local/bin/mysql";
$virtual = "/usr/local/bin/virtualhost.sh";
$brew = "/usr/local/bin/brew";
$unzip = "/usr/bin/unzip";
$rm = "/bin/rm";
$mv = "/bin/mv";
$chmod = "/bin/chmod";
$wget = "/usr/local/bin/wget";
$cp = "/bin/cp";

$dir = "/Users/".$user."/Sites/$pcode";
$themedir = $dir ."/wp-content/themes";
$themezip = "https://downloads.wordpress.org/theme/devdmbootstrap3.1.71.zip";
$themebasename = "devdmbootstrap3";

$startfiles = [];
$startfiles[".htaccess"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/htaccess";
$startfiles[".gitignore"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/gitignore";
$startfiles["languagebounce.php"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/languagebounce.php";
$startfiles["wp-config.local.php"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/wp-config.local.php";
$startfiles["wp-config.staging.php"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/wp-config.staging.php";
$startfiles["wp-config.production.php"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/wp-config.production.php";


$postfiles = [];
$postfiles['wp-content/themes/'.$pcode."/style.css"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/style.css";
$postfiles['wp-content/themes/'.$pcode."/header.php"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/header.php";
$postfiles['wp-content/themes/'.$pcode."/config.rb"] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/config.rb";


$postfiles['wp-content/themes/'.$pcode.'/scss/_base.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_base.scss";

$postfiles['wp-content/themes/'.$pcode.'/scss/_layout/_footer.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_layout/_footer.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_layout/_header.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_layout/_header.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_layout/_main.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_layout/_main.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_layout/_nav.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_layout/_nav.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_layout.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_layout.scss";

$postfiles['wp-content/themes/'.$pcode.'/scss/_mixins/_center.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_mixins/_center.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_mixins/_functions.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_mixins/_functions.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_mixins/_media.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_mixins/_media.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_mixins.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_mixins.scss";

$postfiles['wp-content/themes/'.$pcode.'/scss/_modules/_box.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_modules/_box.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_modules.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_modules.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_site-settings.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_site-settings.scss";

$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/_bootstrap-compass.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/_bootstrap-compass.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/_bootstrap-mincer.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/_bootstrap-mincer.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/_bootstrap-sprockets.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/_bootstrap-sprockets.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/_bootstrap.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/_bootstrap.scss";

$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_alerts.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_alerts.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_badges.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_badges.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_breadcrumbs.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_breadcrumbs.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_button-groups.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_button-groups.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_buttons.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_buttons.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_carousel.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_carousel.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_close.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_close.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_code.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_code.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_component-animations.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_component-animations.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_dropdowns.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_dropdowns.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_forms.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_forms.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_glyphicons.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_glyphicons.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_grid.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_grid.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_input-groups.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_input-groups.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_jumbotron.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_jumbotron.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_labels.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_labels.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_list-group.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_list-group.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_media.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_media.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_mixins.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_mixins.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_modals.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_modals.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_navbar.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_navbar.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_navs.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_navs.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_normalize.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_normalize.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_pager.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_pager.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_pagination.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_pagination.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_panels.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_panels.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_popovers.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_popovers.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_print.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_print.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_progress-bars.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_progress-bars.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_responsive-embed.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_responsive-embed.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_responsive-utilities.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_responsive-utilities.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_scaffolding.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_scaffolding.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_tables.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_tables.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_theme.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_theme.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_thumbnails.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_thumbnails.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_tooltip.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_tooltip.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_type.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_type.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_utilities.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_utilities.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_variables.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_variables.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/_wells.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/_wells.scss";

$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_alerts.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_alerts.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_background-variant.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_background-variant.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_border-radius.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_border-radius.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_buttons.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_buttons.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_center-block.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_center-block.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_clearfix.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_clearfix.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_forms.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_forms.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_gradients.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_gradients.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_grid-framework.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_grid-framework.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_grid.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_grid.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_hide-text.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_hide-text.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_image.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_image.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_labels.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_labels.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_list-group.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_list-group.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_nav-divider.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_nav-divider.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_nav-vertical-align.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_nav-vertical-align.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_opacity.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_opacity.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_pagination.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_pagination.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_panels.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_panels.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_progress-bar.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_progress-bar.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_reset-filter.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_reset-filter.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_reset-text.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_reset-text.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_resize.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_resize.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_responsive-visibility.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_responsive-visibility.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_size.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_size.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_tab-focus.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_tab-focus.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_table-row.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_table-row.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_text-emphasis.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_text-emphasis.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_text-overflow.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_text-overflow.scss";
$postfiles['wp-content/themes/'.$pcode.'/scss/_vendor/bootstrap/mixins/_vendor-prefixes.scss'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/scss/_vendor/bootstrap/mixins/_vendor-prefixes.scss";

$postfiles['wp-content/themes/'.$pcode.'/fonts/bootstrap/glyphicons-halflings-regular.eot'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/fonts/bootstrap/glyphicons-halflings-regular.eot";
$postfiles['wp-content/themes/'.$pcode.'/fonts/bootstrap/glyphicons-halflings-regular.svg'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/fonts/bootstrap/glyphicons-halflings-regular.svg";
$postfiles['wp-content/themes/'.$pcode.'/fonts/bootstrap/glyphicons-halflings-regular.ttf'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/fonts/bootstrap/glyphicons-halflings-regular.ttf";
$postfiles['wp-content/themes/'.$pcode.'/fonts/bootstrap/glyphicons-halflings-regular.woff'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/fonts/bootstrap/glyphicons-halflings-regular.woff";
$postfiles['wp-content/themes/'.$pcode.'/fonts/bootstrap/glyphicons-halflings-regular.woff2'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/fonts/bootstrap/glyphicons-halflings-regular.woff2";

$postfiles['wp-content/themes/'.$pcode.'/js/main.js'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/js/main.js";
$postfiles['wp-content/themes/'.$pcode.'/js/plugins.js'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/js/plugins.js";

$postfiles['wp-content/themes/'.$pcode.'/img/bg/.keep'] = "https://raw.githubusercontent.com/brownrl/wpstrt/master/img/bg/.keep";


$plugins = [];
$plugins['pagebuilder'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/14952d940a53c77efa4a079c7087c48a/siteorigin-panels.2.2.1.zip";
$plugins['gravity'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/cb16899e383b58c2ccd18b64d8e53794/gravityforms.zip";
$plugins['gravitypost'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/d0debb7c78f397bd2a9fd21985a71334/Gravity-HTTP-POST-Plugin.zip";
$plugins['wpml'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/562385b858ab788a5e99ace80f964c14/sitepress-multilingual-cms.zip";
$plugins['wpmlstring'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/2f4ce9aa50dec029a0d274e5ce88dc36/wpml-string-translation.zip";
$plugins['wp-migrate'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/08ae4d2472c781b6b4ce923f96032d43/wp-migrate-db-pro.zip";
$plugins['wp-migrate-media'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/e1d17dca9af8e06727cae6b4c194c75f/wp-migrate-db-pro-media-files.zip";
$plugins['filemanager'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/bf563c1380cecbca06698287bff548ee/wp-filemanager.zip";
$plugins['fields'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/4ce8446a2a009754dcc670c6183b1db7/advanced-custom-fields.zip";
$plugins['tinymce'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/b3b6a34f064f0f7d1978ee7ff2a18aa3/tinymce-advanced.zip";
$plugins['types'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/ba75f6b91e5e0756a104cf5d11afca7f/types.zip";
$plugins['treeeview'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/40f04d5815240df8032d275ce6a4b18b/cms-tree-page-view.1.2.34.zip";
$plugins['imagesizes'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/e1c7b35e1d3909cd6a415e6d1d8833fd/simple-image-sizes.3.0.9.zip";
$plugins['adminglogo'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/1b9407cc145c45c4fa2b665837b4caad/add-logo-to-admin.zip";
$plugins['mediafolder'] = "https://trello-attachments.s3.amazonaws.com/55b6326a7df81eac91936471/565db26fa2a9dcb12f250176/cf4202d6b45a769a88c1a61cf4390a8c/wp-media-folder.zip";




if( ! preg_match( "/^[a-z]{6}$/" , $pcode ) ) {

	echo "You need to have 6 charecter argument passed ex, colweb\n";
    exit( 1 );

}

if( ! file_exists( $brew ) ) {

	echo "Jesus! do you even have the homebrew installed? (google homebrew!)\n";
	exit( 1 );

}


if( ! is_dir( $dir ) ) {

	echo "have you made this project in Beanstalk and cloned it to your local?\n";
	exit( 1 );

}


if( ! file_exists( $wp ) ) {

	echo "Jesus! do you even have the wp-cli installed? (brew install wp-cli)\n";
	exit( 1 );

}

if( ! file_exists( $virtual ) ) {

	echo "Jesus! do you even have the virtualhost.sh installed? (brew install virtualhost.sh)\n";
	exit( 1 );

}

if( ! file_exists( $mysql ) ) {

	echo "Jesus! do you even have the MYSQL installed? (brew install mysql)\n";
	exit( 1 );

}
$mysql .= " -uroot -e";

if( ! file_exists( $wget ) ) {

	echo "Jesus! do you even have the WGET installed? (brew install wget)\n";
	exit( 1 );

}

    // OK we get this far

	echo "\n\n";
	echo "Starting servers if they are not already started\n";
	echo exec( "/usr/bin/sudo /usr/sbin/apachectl start" );
	echo exec( "/usr/local/bin/mysql.server start" );
	echo "\n\n";

	echo exec( $sudo . " " . $chmod . " -R 777 " . $dir );

	// FIRST MYSQL DB
	echo "\n\n";
    echo "Creating Databases $pcode with user $pcode and password $pcode for 127.0.0.1\n\n";
    $q1="CREATE DATABASE IF NOT EXISTS ".$pcode.";";
    $q2="GRANT USAGE ON *.* TO $pcode@127.0.0.1 IDENTIFIED BY '$pcode';";
    $q3="GRANT ALL PRIVILEGES ON ".$pcode.".* TO $pcode@127.0.0.1;";
    $q4="FLUSH PRIVILEGES;";
    $sql='"'.$q1.$q2.$q3.$q4.'"';
    echo exec($mysql.$sql);
    echo "\n\n";


    echo "\n\n";
    chdir( $dir );
    echo "Downloading Wordpress\n\n";
    echo exec($wp . " core download" );
    echo "\n\n";


    echo "\n\n";
    echo "Config Files\n\n";
    foreach( $startfiles as $file => $url ) {
    	file_put_contents( $file, preg_replace( "/XXXXXX/" , $pcode , file_get_contents( $url ) ) );
    }
    copy( "wp-config.local.php" , "wp-config.php" );
    echo "\n\n";



    echo "\n\n";
    echo "Install\n\n";
    echo exec( $wp . " core install --url=http://".$pcode." --title=".$pcode." --admin_user=".$pcode." --admin_password=".$pcode." --admin_email=".$pcode."@".$pcode.".com" );
    echo "\n\n";

    echo "\n\n";
    echo "Theme\n\n";
    file_put_contents( $dir . "/wp-content/themes/theme.zip" , file_get_contents( $themezip ) );
    chdir( $themedir );
    echo exec( $unzip . " -o theme.zip" );
    echo exec( $rm . " theme.zip" );
    echo "\n\n";


    chdir( $dir );
    echo "\n\n";
    echo "Post Files\n\n";

    foreach( $postfiles as $file => $url ) {
    	if( ! is_dir( dirname( $file ) ) ) {
    		mkdir( dirname( $file ) , 0777 , true );
    	}
    	file_put_contents( $file, preg_replace( "/XXXXXX/" , $pcode , file_get_contents( $url ) ) );
    }
    echo "\n\n";

    echo "\n\n";
    echo "Set the theme\n\n";
    echo exec( $wp . " theme activate ".$pcode );
    echo exec( $cp . " " . $themedir . "/" . $themebasename . "/screenshot.png " . $themedir . "/" . $pcode . "/" );
    echo exec( $wp . " theme delete twentyfifteen" );
    echo exec( $wp . " theme delete twentyfourteen" );
    echo exec( $wp . " theme delete twentythirteen" );
    echo exec( $wp . " theme delete twentysixteen" );
    echo "\n\n";





    echo "\n\n";
    echo "Virtualhost.sh\n\n";
    echo exec( $virtual . " " . $pcode );
    echo "\n\n";


    echo "\n\n";
    echo "Permissions\n\n";
    echo exec( $sudo . " " . $chmod . " -R 777 " . $dir );
    echo "\n\n";


    echo "\n\n";
    echo "Plugins\n\n";
    foreach( $plugins as $plugin => $url ) {
    	echo exec( $wp . " plugin install " . $url );
    }
    echo exec( $sudo . " " . $chmod . " -R 777 " . $dir );
    echo "\n\n";




